### ISSUE TITLE
the README example

### ISSUE THREAD

**Issue by jverzani** [BenLauwens/ResumableFunctions.jl#20]
If I run the README example (v"0.6.2", v"0.1.10"), I get an error:

```
ERROR: MethodError: Cannot `convert` an object of type Void to an object of type Int64
```

This is not the case with the slightly different example here: https://benlauwens.github.io/ResumableFunctions.jl/stable/

The issue is the return value of `nothing` at the end of the iteration in the README. Is there some mechanism to only iterate over values explicitly yielded?  (And not the final value returned by the function.) In my usage, it would simplify some algorithms.

**Comment by BenLauwens** [comment]
The `README` is updated yesterday. Check out branch `Python-generators-v0.6`. I will release a new version next week.

**Comment by jverzani** [comment]
Thanks!
