### ISSUE TITLE
type CodeInfo has no field slottypes

### ISSUE THREAD

**Issue by dmitrypenzar1996** [BenLauwens/ResumableFunctions.jl#24]
@resumable function fib_rf()
           prev=0
           cur=1
           while(true)
               @yield cur
               prev, cur = (cur, prev+cur) # nice little avoiding a temp here
           end
       end

Running this simple chunk of code for Julia 1.0 results in Error:
"LoadError: type CodeInfo has no field slottypes"

**Comment by BenLauwens** [comment]
I have just release a version that is Julia v1.0 compatible.
Enjoy!

Ben
