### ISSUE TITLE
Warning: @resumable function contains return statement with value!

### ISSUE THREAD

**Issue by hdavid16** [BenLauwens/ResumableFunctions.jl#47]
Why is this warning being given? Return values are used inside resumable functions to pass something when `@yield` is called on the function.

**Comment by hdavid16** [comment]
As shown in: https://benlauwens.github.io/SimJulia.jl/stable/guides/environments.html#Miscellaneous-1

**Comment by BenLauwens** [comment]
Sorry for the late reply ... a normal return ends the resumable function and to mimic the iteration interface nothing should be returned ... The docs of SimJulia will be reviewed in 2021!
