### ISSUE TITLE
`continue` results in infinite loops

### ISSUE THREAD

**Issue by ghost** [BenLauwens/ResumableFunctions.jl#53]
The following hangs:
 
```julia
julia> using ResumableFunctions

julia> @resumable function f()
           for i in 1:10
               i % 2 == 0 && continue
               @yield i
           end
       end
f (generic function with 1 method)

julia> collect(f())
```

Adding a line to print out `i` shows that the loop goes through once with `i = 1`, then repeats the loop body forever with `i = 2`.

**Comment by hdavid16** [comment]
Hi @cpsquonk, I observed the same behavior. What I ended up doing was using an `if` statement instead of the `continue`:

```julia
@resumable function f()
    for i in 1:10
        if i % 2 != 0
            @yield i
        end
    end
end
```

**Comment by BenLauwens** [comment]
Hi

The `for` iterator loop is transformed into a `while` loop. The update of the iterator is done just before the `end` keyword of the loop ... so `continue` skips the update and the iterator does not advance...
I suppose that `continue` is replaced by a local jump. Something similar has to be implemented.
I keep you informed of possible progress

Kind regards

Ben

**Comment by BenLauwens** [comment]
I had a really productive evening;) This should work now! Feedback is welcome!
