### ISSUE TITLE
Resumable functions do not recognize types in same module

### ISSUE THREAD

**Issue by ianfiske** [BenLauwens/ResumableFunctions.jl#9]
If we define a `@resumable` function in a module, using a type defined in the same module as an argument type, we get an error:

```
module testresumable

using SimJulia, ResumableFunctions

struct A
    x::Float64
end

@resumable function myprocess(sim::Simulation, a::A)
    @yield timeout(sim, 10)
end

end
```

This gives the error `UndefVarError: A not defined`.  I am using
- ResumableFunctions 0.1.5
- MacroTools 0.4.0
- Julia 0.6.0
- Mac OS X

**Comment by BenLauwens** [comment]
The problem is caused by an (evil) `eval` statement in `utils.jl`. This is needed for type inference ... 
I have added a fix to the master branch. (`Pkg.checkout("ResumableFunctions")`) 
Can you verify that this solves your problem? If so I will do a new release. Thanks

**Comment by ianfiske** [comment]
I just verified that your update works for me in master.  Thank you for the fix!
